package: virtual_urls
version: '0.1.0'
author: KLXM
supportpage: https://github.com/KLXM/virtual_urls

requires:
    redaxo: '^5.10.0'
    packages:
        yrewrite: '>=2.0'
        yform: '>=4.0'

page:
    title: 'Virtual URLs'
    perm: admin
    icon: rex-icon fa-road
    subpages:
        profiles:
            title: 'Profile'
            icon: rex-icon fa-list
        help:
            title: 'URLs & Tester'
            icon: rex-icon fa-search
        tools:
            title: 'Slug-Generator'
            icon: rex-icon fa-cogs
        docs:
            title: 'Hilfe'
            icon: rex-icon fa-question-circle
